select * from forests;
select * from Tree_Planting_Projects_donors;
select * from IsFor;
select * from HasA;
select * from Trees;
select * from Tree_Planting_Projects;
select * from Education_Programs;
select * from Forest_Fire_Prevention_Actions;
select * from Research_Stations;
