insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (1, 'Sustainable Seeds Program', null, 'all', 284);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (2, 'Green Horizons Academy', null, 'all', 220);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (3, 'Green Horizons Academy', 'environmental science', 'all', 214);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (4, 'EcoLeaders Learning Hub', 'Biodiversity Surveys', 'toddlers', 187);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (5, 'Sustainability Quest Academy', 'Leaf Pressing', 'all', 16);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (6, 'Green Pathways Program', 'hike', 'tweens', 372);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (7, 'Nature''s Classroom Network', 'meaningful', 'toddlers', 129);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (8, 'Blue Planet Learning Center', 'history of the forest', 'family', 135);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (9, 'Sustainable Scholars Network', 'environmental science', 'tweens', 235);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (10, 'Green Pathways Program', 'wildlife observation', 'toddlers', 130);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (11, 'Sustainable Future Scholars', null, 'groups', 180);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (12, 'Wildlife Warriors Program', 'Leaf Pressing', 'teens', 357);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (13, 'EcoSavvy School Project', 'environmental science', 'schools', 266);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (14, 'EarthWise Education Initiative', 'environmental science', 'seniors', 385);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (15, 'Planet Pioneers Academy', 'guided', 'all', 184);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (16, 'Earth Guardians Academy', 'guided', 'all', 264);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (17, 'Earth Guardians Academy', 'local', 'schools', 335);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (18, 'Sustainable Seeds Program', 'Tree Identification', 'schools', 373);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (19, 'Planet Protectors Initiative', 'Forest Photography', 'all', 51);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (20, 'EcoSavvy School Project', null, 'couples', 321);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (21, 'Sustainable Scholars Network', null, 'tweens', 318);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (22, 'EcoLeaders Learning Hub', 'Soil Testing', 'all', 51);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (23, 'Green Trails Education Initiative', null, 'groups', 310);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (24, 'Green Guardians Program', 'Biodiversity Surveys', 'all', 355);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (25, 'Sustainable Seeds Program', 'meaningful', 'all', 64);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (26, 'Earth Guardians Academy', 'Insect Study', 'adults', 208);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (27, 'Eco Innovators Institute', 'Forest Photography', 'all', 272);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (28, 'Sustainability Starters Program', 'Mapping', 'schools', 198);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (29, 'EcoLeaders Learning Hub', 'wildlife observation', 'couples', 231);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (30, 'Eco Future Foundation', null, 'toddlers', 90);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (31, 'EcoVision Learning Center', 'Forest Photography', 'all', 54);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (32, 'Earth Ambassadors Program', 'adventurous', 'adults', 340);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (33, 'Eco Innovators Institute', 'Mapping', 'kids', 131);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (34, 'Sustainability Quest Academy', 'climate changes', 'teens', 351);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (35, 'Green Planet Academy', 'wildlife observation', 'seniors', 160);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (36, 'Sustainable Seeds Program', 'Insect Study', 'family', 160);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (37, 'Green Earth Explorers', 'Tree Identification', 'toddlers', 153);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (38, 'Blue Planet Learning Center', null, 'all', 164);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (39, 'Eco Innovators Institute', 'Insect Study', 'couples', 13);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (40, 'Green Trails Education Initiative', 'habitat restoration', 'kids', 281);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (41, 'EcoLeaders Learning Hub', 'wildlife observation', 'tweens', 185);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (42, 'Green Earth Explorers', 'adventurous', 'all', 352);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (43, 'Eco Pioneers Program', null, 'seniors', 296);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (44, 'Eco Explorers Club', 'guided', 'adults', 389);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (45, 'EcoSavvy School Project', 'animal habitat', 'all', 190);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (46, 'Sustainable Seeds Program', 'history of the forest', 'adults', 383);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (47, 'Eco Explorers Club', 'Insect Study', 'all', 162);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (48, 'EcoSavvy School Project', 'Survival Skills', 'all', 298);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (49, 'EcoSavvy School Project', 'local', 'adults', 172);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (50, 'EarthWise Education Initiative', 'Mapping', 'schools', 34);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (51, 'Sustainable Seeds Program', 'habitat restoration', 'all', 74);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (52, 'Eco Horizon Project', 'animal habitat', 'tweens', 182);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (53, 'EcoVision Learning Center', 'local', 'couples', 213);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (54, 'Blue Planet Learning Center', 'climate changes', 'tweens', 7);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (55, 'Sustainability Quest Academy', 'Biodiversity Surveys', 'all', 161);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (56, 'Planet Protectors Initiative', 'adventurous', 'groups', 20);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (57, 'Planet Protectors Initiative', 'climate changes', 'adults', 173);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (58, 'Green Generation Labs', 'Mapping', 'toddlers', 156);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (59, 'Green Guardians Program', 'ecosystems', 'schools', 281);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (60, 'Eco Horizon Project', 'habitat restoration', 'all', 359);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (61, 'Green Planet Academy', 'ecosystems', 'toddlers', 86);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (62, 'Earth Guardians Academy', 'Insect Study', 'toddlers', 366);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (63, 'Planet Protectors Initiative', 'Soil Testing', 'couples', 395);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (64, 'Sustainability Starters Program', 'wildlife observation', 'all', 277);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (65, 'EcoSavvy School Project', 'Survival Skills', 'kids', 122);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (66, 'Eco Future Foundation', 'history of the forest', 'groups', 246);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (67, 'Nature''s Wisdom School', 'local', 'tweens', 271);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (68, 'Nature''s Wisdom School', 'Insect Study', 'groups', 391);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (69, 'EcoLeaders Learning Hub', 'wildlife observation', 'schools', 160);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (70, 'Earth Guardians Academy', 'Soil Testing', 'all', 375);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (71, 'EcoVision Learning Center', 'Leaf Pressing', 'groups', 20);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (72, 'Green Planet Academy', 'wildlife observation', 'toddlers', 253);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (73, 'Sustainability Starters Program', 'hike', 'seniors', 287);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (74, 'Eco Horizon Project', null, 'teens', 178);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (75, 'Earth Guardians Academy', null, 'schools', 225);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (76, 'Nature''s Wisdom School', 'local', 'all', 273);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (77, 'Sustainability Starters Program', 'Leaf Pressing', 'all', 215);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (78, 'EcoLeaders Learning Hub', 'Survival Skills', 'seniors', 331);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (79, 'Green Guardians Program', 'Leaf Pressing', 'all', 192);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (80, 'Green Horizons Academy', 'ecosystems', 'tweens', 126);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (81, 'Planet Protectors Initiative', 'Night Hikes', 'tweens', 139);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (82, 'Planet Protectors Initiative', 'animal habitat', 'all', 6);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (83, 'Green Planet Academy', null, 'family', 277);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (84, 'Eco Innovators Institute', 'hike', 'seniors', 44);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (85, 'Wildlife Warriors Program', 'wildlife observation', 'teens', 65);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (86, 'Sustainable Seeds Program', 'local', 'all', 301);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (87, 'Sustainability Quest Academy', 'Survival Skills', 'all', 130);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (88, 'Planet Protectors Initiative', 'animal habitat', 'all', 37);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (89, 'Sustainable Scholars Network', 'ecosystems', 'seniors', 37);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (90, 'Green Earth Explorers', 'climate changes', 'adults', 314);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (91, 'Sustainable Seeds Program', null, 'all', 393);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (92, 'Eco Horizon Project', 'Tree Identification', 'family', 40);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (93, 'Sustainability Quest Academy', 'habitat restoration', 'all', 129);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (94, 'Eco Innovators Institute', 'Leaf Pressing', 'family', 372);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (95, 'EcoLeaders Learning Hub', 'Survival Skills', 'all', 310);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (96, 'Earth Guardians Academy', 'Insect Study', 'tweens', 171);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (97, 'Earth Guardians Academy', 'ecosystems', 'all', 66);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (98, 'Climate Champions Academy', 'history of the forest', 'schools', 228);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (99, 'EarthWise Education Initiative', 'Night Hikes', 'kids', 260);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (100, 'Eco Explorers Club', 'history of the forest', 'all', 173);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (101, 'Green Generation Labs', 'animal habitat', 'tweens', 302);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (102, 'Green Earth Explorers', 'Mapping', 'all', 12);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (103, 'Green Pathways Program', 'Mapping', 'kids', 27);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (104, 'Eco Pioneers Program', 'ecosystems', 'groups', 39);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (105, 'Eco Pioneers Program', 'Leaf Pressing', 'toddlers', 372);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (106, 'Blue Planet Learning Center', 'Night Hikes', 'teens', 232);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (107, 'Sustainable Future Scholars', 'environmental science', 'seniors', 273);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (108, 'Sustainable Future Scholars', 'local', 'family', 181);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (109, 'Sustainability Starters Program', 'ecosystems', 'family', 7);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (110, 'Nature''s Classroom Network', 'hike', 'all', 94);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (111, 'Nature''s Classroom Network', 'adventurous', 'couples', 355);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (112, 'Sustainability Quest Academy', null, 'kids', 248);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (113, 'Planet Pioneers Academy', 'habitat restoration', 'couples', 334);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (114, 'EcoLeaders Learning Hub', 'climate changes', 'family', 287);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (115, 'Green Guardians Program', 'local', 'teens', 64);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (116, 'Sustainability Quest Academy', 'environmental science', 'seniors', 309);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (117, 'EcoLeaders Learning Hub', 'environmental science', 'couples', 10);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (118, 'Green Earth Explorers', 'Forest Photography', 'toddlers', 340);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (119, 'EcoVision Learning Center', 'habitat restoration', 'kids', 244);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (120, 'Nature''s Wisdom School', null, 'toddlers', 6);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (121, 'Sustainable Seeds Program', 'Tree Identification', 'seniors', 7);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (122, 'Eco Explorers Club', 'history of the forest', 'kids', 249);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (123, 'Earth Guardians Academy', 'adventurous', 'family', 147);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (124, 'Sustainable Future Scholars', 'local', 'kids', 231);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (125, 'Green Trails Education Initiative', 'animal habitat', 'groups', 398);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (126, 'Wildlife Warriors Program', 'environmental science', 'couples', 108);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (127, 'Sustainable Seeds Program', 'ecosystems', 'all', 69);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (128, 'Green Earth Explorers', 'Night Hikes', 'teens', 278);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (129, 'Earth Guardians Academy', 'guided', 'seniors', 161);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (130, 'EarthWise Education Initiative', 'environmental science', 'toddlers', 392);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (131, 'Green Trails Education Initiative', 'ecosystems', 'groups', 159);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (132, 'Eco Explorers Club', 'Leaf Pressing', 'kids', 207);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (133, 'Green Planet Academy', null, 'teens', 297);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (134, 'Wildlife Warriors Program', null, 'seniors', 39);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (135, 'Green Pathways Program', 'environmental science', 'adults', 396);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (136, 'Green Generation Labs', 'Mapping', 'schools', 354);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (137, 'Nature''s Classroom Network', 'environmental science', 'teens', 251);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (138, 'Nature''s Classroom Network', 'climate changes', 'adults', 162);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (139, 'EcoSavvy School Project', null, 'all', 277);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (140, 'Sustainable Scholars Network', 'local', 'schools', 140);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (141, 'Green Trails Education Initiative', null, 'teens', 243);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (142, 'Sustainable Scholars Network', 'climate changes', 'adults', 299);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (143, 'Nature''s Wisdom School', 'local', 'groups', 296);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (144, 'Eco Horizon Project', 'animal habitat', 'adults', 368);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (145, 'Green Planet Academy', 'wildlife observation', 'couples', 168);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (146, 'EcoVision Learning Center', 'Night Hikes', 'toddlers', 63);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (147, 'EcoSavvy School Project', 'wildlife observation', 'teens', 214);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (148, 'Green Trails Education Initiative', 'Night Hikes', 'family', 100);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (149, 'EcoLeaders Learning Hub', 'Mapping', 'schools', 9);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (150, 'EcoVision Learning Center', 'Biodiversity Surveys', 'schools', 81);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (151, 'Green Earth Explorers', 'Survival Skills', 'all', 275);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (152, 'EcoVision Learning Center', null, 'seniors', 72);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (153, 'EcoSavvy School Project', 'Biodiversity Surveys', 'all', 128);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (154, 'EcoLeaders Learning Hub', 'ecosystems', 'seniors', 309);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (155, 'Eco Pioneers Program', 'Insect Study', 'all', 71);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (156, 'Sustainable Seeds Program', 'climate changes', 'couples', 10);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (157, 'EcoSavvy School Project', 'animal habitat', 'groups', 234);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (158, 'Eco Pioneers Program', 'guided', 'all', 370);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (159, 'Blue Planet Learning Center', 'hands-on', 'couples', 43);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (160, 'Green Horizons Academy', 'guided', 'adults', 310);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (161, 'Earth Guardians Academy', 'history of the forest', 'all', 208);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (162, 'EcoSavvy School Project', 'hands-on', 'all', 72);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (163, 'Planet Protectors Initiative', 'Soil Testing', 'couples', 119);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (164, 'Sustainability Starters Program', 'guided', 'all', 227);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (165, 'Green Generation Labs', 'environmental science', 'schools', 227);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (166, 'EarthWise Education Initiative', 'climate changes', 'all', 206);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (167, 'Blue Planet Learning Center', 'climate changes', 'kids', 26);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (168, 'EarthWise Education Initiative', 'climate changes', 'toddlers', 264);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (169, 'Eco Explorers Club', 'Soil Testing', 'all', 176);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (170, 'Earth Guardians Academy', null, 'kids', 33);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (171, 'Green Guardians Program', 'Survival Skills', 'seniors', 235);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (172, 'Green Horizons Academy', null, 'kids', 77);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (173, 'Green Planet Academy', 'guided', 'all', 247);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (174, 'Nature''s Wisdom School', 'hike', 'all', 213);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (175, 'EcoVision Learning Center', 'Survival Skills', 'kids', 259);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (176, 'Nature''s Classroom Network', 'hike', 'toddlers', 161);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (177, 'Climate Champions Academy', 'hike', 'schools', 327);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (178, 'Wildlife Warriors Program', null, 'all', 96);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (179, 'Green Guardians Program', 'Biodiversity Surveys', 'all', 341);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (180, 'Sustainability Quest Academy', 'climate changes', 'seniors', 341);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (181, 'Eco Innovators Institute', 'Survival Skills', 'family', 318);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (182, 'Sustainable Scholars Network', 'history of the forest', 'family', 285);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (183, 'Green Planet Academy', 'local', 'couples', 344);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (184, 'Nature''s Wisdom School', 'Insect Study', 'all', 7);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (185, 'Nature''s Wisdom School', 'hike', 'groups', 196);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (186, 'Eco Innovators Institute', 'meaningful', 'schools', 200);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (187, 'Nature''s Classroom Network', 'climate changes', 'teens', 4);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (188, 'Green Trails Education Initiative', 'Insect Study', 'groups', 45);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (189, 'Eco Horizon Project', 'wildlife observation', 'all', 218);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (190, 'Nature''s Wisdom School', 'animal habitat', 'kids', 381);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (191, 'EarthWise Education Initiative', 'Biodiversity Surveys', 'toddlers', 361);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (192, 'Sustainability Quest Academy', 'history of the forest', 'kids', 263);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (193, 'Green Generation Labs', 'local', 'schools', 176);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (194, 'Eco Explorers Club', null, 'schools', 57);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (195, 'Green Earth Explorers', 'environmental science', 'toddlers', 164);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (196, 'Green Earth Explorers', 'Soil Testing', 'seniors', 280);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (197, 'Green Horizons Academy', 'local', 'toddlers', 217);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (198, 'Green Guardians Program', 'hike', 'teens', 249);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (199, 'Nature''s Classroom Network', 'climate changes', 'toddlers', 216);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (200, 'Eco Horizon Project', 'Survival Skills', 'all', 353);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (201, 'EcoLeaders Learning Hub', 'local', 'tweens', 221);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (202, 'Sustainable Future Scholars', 'Leaf Pressing', 'seniors', 315);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (203, 'Green Horizons Academy', 'history of the forest', 'all', 387);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (204, 'Eco Future Foundation', 'guided', 'seniors', 358);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (205, 'Green Trails Education Initiative', 'history of the forest', 'seniors', 296);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (206, 'Sustainable Future Scholars', 'Tree Identification', 'schools', 124);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (207, 'Green Guardians Program', 'hike', 'kids', 166);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (208, 'Climate Champions Academy', 'Biodiversity Surveys', 'kids', 366);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (209, 'Green Pathways Program', null, 'teens', 28);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (210, 'EarthWise Education Initiative', 'Insect Study', 'family', 344);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (211, 'Eco Horizon Project', 'Biodiversity Surveys', 'toddlers', 194);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (212, 'Green Generation Labs', 'Night Hikes', 'all', 310);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (213, 'Green Pathways Program', 'local', 'teens', 254);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (214, 'EcoVision Learning Center', 'Insect Study', 'adults', 49);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (215, 'Sustainability Starters Program', 'Tree Identification', 'all', 15);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (216, 'Sustainability Starters Program', 'environmental science', 'all', 6);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (217, 'Planet Pioneers Academy', 'hike', 'adults', 58);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (218, 'Wildlife Warriors Program', 'adventurous', 'all', 331);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (219, 'Nature''s Classroom Network', 'Leaf Pressing', 'kids', 152);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (220, 'Sustainable Scholars Network', 'Insect Study', 'seniors', 224);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (221, 'Sustainable Seeds Program', 'local', 'kids', 379);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (222, 'Green Pathways Program', 'ecosystems', 'all', 391);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (223, 'Green Horizons Academy', 'local', 'toddlers', 365);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (224, 'Sustainability Starters Program', null, 'all', 374);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (225, 'Nature''s Wisdom School', 'Survival Skills', 'teens', 153);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (226, 'EcoLeaders Learning Hub', 'guided', 'couples', 387);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (227, 'EcoVision Learning Center', 'Biodiversity Surveys', 'all', 153);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (228, 'Green Earth Explorers', 'adventurous', 'all', 377);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (229, 'Eco Innovators Institute', 'habitat restoration', 'toddlers', 334);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (230, 'Green Pathways Program', 'hands-on', 'teens', 16);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (231, 'Sustainability Starters Program', null, 'all', 180);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (232, 'Eco Pioneers Program', 'Insect Study', 'adults', 377);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (233, 'Blue Planet Learning Center', 'history of the forest', 'family', 44);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (234, 'Climate Champions Academy', 'meaningful', 'family', 277);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (235, 'Wildlife Warriors Program', 'Leaf Pressing', 'teens', 356);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (236, 'EcoSavvy School Project', 'Biodiversity Surveys', 'all', 300);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (237, 'Eco Innovators Institute', 'local', 'couples', 291);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (238, 'Green Planet Academy', 'Soil Testing', 'teens', 30);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (239, 'Green Generation Labs', 'Leaf Pressing', 'tweens', 387);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (240, 'Nature''s Wisdom School', 'hands-on', 'all', 3);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (241, 'Sustainable Scholars Network', 'hike', 'schools', 128);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (242, 'EcoSavvy School Project', 'Biodiversity Surveys', 'teens', 160);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (243, 'Sustainable Seeds Program', 'Survival Skills', 'all', 103);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (244, 'EcoSavvy School Project', 'animal habitat', 'family', 261);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (245, 'Green Earth Explorers', 'Tree Identification', 'all', 337);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (246, 'EcoLeaders Learning Hub', 'hike', 'adults', 24);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (247, 'Sustainable Scholars Network', 'climate changes', 'all', 35);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (248, 'Earth Guardians Academy', 'environmental science', 'schools', 103);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (249, 'Sustainability Quest Academy', 'Night Hikes', 'adults', 363);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (250, 'EcoSavvy School Project', 'local', 'teens', 154);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (251, 'Eco Horizon Project', 'history of the forest', 'teens', 302);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (252, 'Green Generation Labs', 'Night Hikes', 'adults', 32);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (253, 'Wildlife Warriors Program', 'meaningful', 'seniors', 384);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (254, 'Green Trails Education Initiative', 'Tree Identification', 'family', 310);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (255, 'EarthWise Education Initiative', 'guided', 'toddlers', 34);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (256, 'Eco Innovators Institute', 'ecosystems', 'groups', 303);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (257, 'Eco Pioneers Program', 'Insect Study', 'teens', 255);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (258, 'Earth Guardians Academy', 'hike', 'groups', 113);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (259, 'Sustainable Scholars Network', 'Survival Skills', 'all', 64);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (260, 'EcoLeaders Learning Hub', 'Mapping', 'all', 395);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (261, 'Eco Future Foundation', 'Night Hikes', 'kids', 175);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (262, 'Green Pathways Program', null, 'all', 199);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (263, 'Climate Champions Academy', 'environmental science', 'family', 227);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (264, 'EcoVision Learning Center', 'Insect Study', 'all', 67);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (265, 'Wildlife Warriors Program', 'animal habitat', 'couples', 243);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (266, 'EarthWise Education Initiative', 'local', 'all', 17);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (267, 'Eco Pioneers Program', 'history of the forest', 'seniors', 304);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (268, 'EcoSavvy School Project', 'Mapping', 'couples', 218);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (269, 'Nature''s Classroom Network', 'Insect Study', 'toddlers', 31);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (270, 'Wildlife Warriors Program', 'wildlife observation', 'schools', 128);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (271, 'Wildlife Warriors Program', 'Survival Skills', 'seniors', 97);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (272, 'Eco Innovators Institute', 'local', 'groups', 5);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (273, 'Planet Pioneers Academy', 'wildlife observation', 'groups', 166);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (274, 'Green Generation Labs', 'Mapping', 'kids', 63);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (275, 'EcoSavvy School Project', 'meaningful', 'kids', 42);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (276, 'Climate Champions Academy', 'Forest Photography', 'all', 122);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (277, 'Sustainable Scholars Network', 'Leaf Pressing', 'teens', 185);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (278, 'Green Guardians Program', 'wildlife observation', 'tweens', 200);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (279, 'Blue Planet Learning Center', 'Mapping', 'all', 86);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (280, 'Green Trails Education Initiative', 'wildlife observation', 'groups', 15);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (281, 'Green Planet Academy', 'meaningful', 'toddlers', 312);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (282, 'EcoSavvy School Project', 'meaningful', 'all', 174);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (283, 'Eco Horizon Project', 'history of the forest', 'kids', 152);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (284, 'Climate Champions Academy', 'adventurous', 'teens', 372);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (285, 'Sustainable Future Scholars', 'wildlife observation', 'all', 243);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (286, 'Wildlife Warriors Program', 'Tree Identification', 'seniors', 273);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (287, 'Nature''s Classroom Network', null, 'toddlers', 75);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (288, 'Eco Explorers Club', 'habitat restoration', 'all', 233);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (289, 'Blue Planet Learning Center', 'Tree Identification', 'family', 188);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (290, 'Nature''s Wisdom School', 'guided', 'seniors', 287);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (291, 'Climate Champions Academy', 'Tree Identification', 'seniors', 298);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (292, 'Green Planet Academy', 'guided', 'groups', 348);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (293, 'Sustainable Scholars Network', null, 'family', 209);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (294, 'Green Horizons Academy', 'Biodiversity Surveys', 'seniors', 214);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (295, 'Sustainability Quest Academy', null, 'all', 54);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (296, 'Eco Innovators Institute', 'Night Hikes', 'couples', 188);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (297, 'Planet Protectors Initiative', 'climate changes', 'family', 331);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (298, 'Green Trails Education Initiative', 'adventurous', 'all', 231);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (299, 'Green Planet Academy', 'environmental science', 'adults', 199);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (300, 'Eco Pioneers Program', 'Forest Photography', 'teens', 380);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (301, 'Sustainability Quest Academy', 'Night Hikes', 'all', 154);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (302, 'Earth Guardians Academy', 'Mapping', 'schools', 128);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (303, 'Earth Guardians Academy', 'hike', 'teens', 371);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (304, 'Sustainability Starters Program', 'ecosystems', 'kids', 382);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (305, 'Climate Champions Academy', 'hands-on', 'all', 141);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (306, 'Earth Guardians Academy', 'wildlife observation', 'groups', 292);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (307, 'Green Earth Explorers', 'ecosystems', 'toddlers', 140);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (308, 'Eco Innovators Institute', null, 'couples', 123);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (309, 'Sustainable Future Scholars', null, 'couples', 71);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (310, 'EcoVision Learning Center', 'meaningful', 'groups', 103);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (311, 'Eco Explorers Club', 'hands-on', 'kids', 283);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (312, 'Sustainable Seeds Program', 'Night Hikes', 'couples', 213);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (313, 'Climate Champions Academy', 'environmental science', 'couples', 73);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (314, 'Planet Protectors Initiative', 'history of the forest', 'teens', 113);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (315, 'Sustainable Scholars Network', 'adventurous', 'all', 75);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (316, 'Sustainable Future Scholars', null, 'adults', 252);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (317, 'EcoSavvy School Project', 'history of the forest', 'kids', 185);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (318, 'Green Trails Education Initiative', 'Leaf Pressing', 'all', 374);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (319, 'Sustainable Seeds Program', 'Leaf Pressing', 'seniors', 135);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (320, 'Green Trails Education Initiative', 'Survival Skills', 'adults', 354);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (321, 'Sustainable Scholars Network', 'ecosystems', 'all', 195);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (322, 'Earth Ambassadors Program', 'Leaf Pressing', 'groups', 61);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (323, 'Sustainability Starters Program', 'hike', 'adults', 168);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (324, 'Green Trails Education Initiative', 'Leaf Pressing', 'family', 10);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (325, 'Eco Innovators Institute', 'habitat restoration', 'tweens', 262);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (326, 'Earth Guardians Academy', 'hike', 'schools', 355);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (327, 'EcoVision Learning Center', 'Tree Identification', 'all', 75);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (328, 'Planet Pioneers Academy', 'history of the forest', 'schools', 237);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (329, 'Planet Pioneers Academy', 'ecosystems', 'kids', 6);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (330, 'Sustainable Scholars Network', 'hike', 'all', 97);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (331, 'Wildlife Warriors Program', 'animal habitat', 'family', 309);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (332, 'EcoLeaders Learning Hub', 'climate changes', 'schools', 220);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (333, 'Sustainable Future Scholars', 'Leaf Pressing', 'all', 305);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (334, 'Blue Planet Learning Center', 'Forest Photography', 'teens', 279);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (335, 'Eco Future Foundation', 'Soil Testing', 'couples', 50);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (336, 'Green Earth Explorers', null, 'all', 271);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (337, 'Planet Protectors Initiative', 'climate changes', 'kids', 18);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (338, 'Green Guardians Program', 'climate changes', 'teens', 232);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (339, 'Green Generation Labs', 'hands-on', 'groups', 238);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (340, 'Sustainable Seeds Program', 'animal habitat', 'seniors', 268);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (341, 'EcoLeaders Learning Hub', null, 'couples', 339);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (342, 'Blue Planet Learning Center', null, 'all', 202);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (343, 'Wildlife Warriors Program', 'guided', 'couples', 162);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (344, 'Wildlife Warriors Program', 'Biodiversity Surveys', 'adults', 157);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (345, 'Sustainable Seeds Program', 'habitat restoration', 'kids', 32);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (346, 'Sustainable Seeds Program', 'Survival Skills', 'all', 234);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (347, 'Planet Protectors Initiative', 'Mapping', 'groups', 177);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (348, 'Eco Horizon Project', 'animal habitat', 'all', 191);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (349, 'Eco Innovators Institute', 'meaningful', 'family', 14);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (350, 'Sustainability Quest Academy', 'hands-on', 'all', 85);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (351, 'Sustainable Seeds Program', 'Night Hikes', 'family', 273);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (352, 'Nature''s Classroom Network', 'Survival Skills', 'adults', 343);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (353, 'Wildlife Warriors Program', 'Biodiversity Surveys', 'seniors', 332);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (354, 'Sustainable Scholars Network', 'Biodiversity Surveys', 'couples', 352);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (355, 'Green Earth Explorers', null, 'schools', 184);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (356, 'Nature''s Wisdom School', null, 'toddlers', 278);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (357, 'Eco Pioneers Program', 'meaningful', 'all', 360);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (358, 'Sustainable Scholars Network', 'meaningful', 'adults', 115);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (359, 'Sustainable Seeds Program', 'hands-on', 'toddlers', 305);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (360, 'Eco Future Foundation', 'Leaf Pressing', 'all', 239);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (361, 'Planet Pioneers Academy', 'habitat restoration', 'toddlers', 60);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (362, 'Eco Horizon Project', 'Forest Photography', 'all', 164);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (363, 'EcoLeaders Learning Hub', 'wildlife observation', 'adults', 263);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (364, 'Green Trails Education Initiative', 'Biodiversity Surveys', 'groups', 250);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (365, 'Planet Protectors Initiative', 'adventurous', 'schools', 167);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (366, 'Blue Planet Learning Center', 'local', 'teens', 11);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (367, 'Earth Guardians Academy', 'Leaf Pressing', 'family', 165);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (368, 'Nature''s Wisdom School', 'adventurous', 'all', 7);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (369, 'EarthWise Education Initiative', 'Night Hikes', 'all', 207);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (370, 'Eco Explorers Club', 'Insect Study', 'seniors', 242);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (371, 'Eco Horizon Project', 'hands-on', 'teens', 15);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (372, 'Blue Planet Learning Center', 'Biodiversity Surveys', 'family', 247);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (373, 'Blue Planet Learning Center', 'Mapping', 'couples', 212);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (374, 'Green Pathways Program', 'Night Hikes', 'all', 14);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (375, 'Sustainable Seeds Program', 'local', 'all', 346);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (376, 'Green Earth Explorers', 'Forest Photography', 'toddlers', 308);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (377, 'Green Pathways Program', null, 'all', 321);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (378, 'EcoVision Learning Center', 'Forest Photography', 'kids', 292);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (379, 'Eco Explorers Club', 'wildlife observation', 'all', 140);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (380, 'Sustainability Starters Program', 'hike', 'couples', 144);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (381, 'Sustainable Seeds Program', 'Soil Testing', 'groups', 112);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (382, 'Nature''s Classroom Network', 'Biodiversity Surveys', 'all', 41);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (383, 'Sustainability Quest Academy', null, 'toddlers', 274);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (384, 'Nature''s Wisdom School', 'Survival Skills', 'kids', 236);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (385, 'Climate Champions Academy', 'Mapping', 'kids', 184);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (386, 'Eco Pioneers Program', 'Insect Study', 'all', 44);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (387, 'Planet Pioneers Academy', 'Mapping', 'teens', 129);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (388, 'Earth Guardians Academy', 'Insect Study', 'family', 15);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (389, 'Green Horizons Academy', 'environmental science', 'couples', 289);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (390, 'Green Horizons Academy', 'Forest Photography', 'all', 29);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (391, 'Green Pathways Program', 'Leaf Pressing', 'all', 139);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (392, 'EcoLeaders Learning Hub', 'Soil Testing', 'toddlers', 15);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (393, 'Green Earth Explorers', 'environmental science', 'kids', 243);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (394, 'EcoVision Learning Center', 'Soil Testing', 'groups', 225);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (395, 'Sustainable Future Scholars', 'Leaf Pressing', 'family', 110);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (396, 'Sustainable Future Scholars', 'animal habitat', 'adults', 228);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (397, 'Sustainable Scholars Network', 'Leaf Pressing', 'seniors', 244);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (398, 'EarthWise Education Initiative', 'climate changes', 'all', 267);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (399, 'Blue Planet Learning Center', 'ecosystems', 'all', 12);
insert into EDUCATION_PROGRAMS (PROGRAM_ID, PROGRAM_NAME, PROGRAM_DESCRIPTION, AGES, STATION_ID) values (400, 'Earth Guardians Academy', 'adventurous', 'all', 338);
