insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (1, 'Burning the Cuttings', 955.95, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (2, 'Pruning', 900.61, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (3, 'Sanitation', 947.41, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (4, 'Watchtowers', 694.34, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (5, 'Burning the Cuttings', 187.04, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (6, 'Pruning', 621.32, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (7, 'Removing the Cuttings and the Tree Waste', 976.33, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (8, 'Thinning', 187.05, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (9, 'Pruning', 493.45, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (10, 'Water', 354.13, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (11, 'Firebreaks', 435.16, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (12, 'Water', 120.74, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (13, 'Firebreaks', 343.33, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (14, 'Watchtowers', 583.31, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (15, 'Removing the Cuttings and the Tree Waste', 315.21, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (16, 'Sanitation', 807.46, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (17, 'Pruning', 95.85, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (18, 'Water', 157.87, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (19, 'Sanitation', 253.36, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (20, 'Pruning', 437.31, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (21, 'Removing the Cuttings and the Tree Waste', 832.34, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (22, 'Sanitation', 604.13, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (23, 'Sanitation', 691.03, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (24, 'access roads', 198.86, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (25, 'Watchtowers', 223.0, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (26, 'Removing the Cuttings and the Tree Waste', 774.3, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (27, 'Firebreaks', 531.89, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (28, 'Firebreaks', 288.13, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (29, 'Thinning', 480.34, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (30, 'Removing the Cuttings and the Tree Waste', 814.58, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (31, 'Firebreaks', 506.83, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (32, 'Firebreaks', 403.53, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (33, 'Firebreaks', 807.45, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (34, 'Burning the Cuttings', 525.33, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (35, 'Water', 600.36, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (36, 'Water', 95.74, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (37, 'Firebreaks', 627.19, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (38, 'Water', 314.04, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (39, 'Burning the Cuttings', 230.89, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (40, 'Burning the Cuttings', 526.1, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (41, 'Burning the Cuttings', 64.91, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (42, 'access roads', 29.85, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (43, 'Signposting', 112.65, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (44, 'Signposting', 518.07, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (45, 'Sanitation', 443.67, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (46, 'Firebreaks', 901.89, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (47, 'Water', 10.05, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (48, 'Firebreaks', 96.58, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (49, 'Sanitation', 959.19, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (50, 'access roads', 491.63, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (51, 'Pruning', 107.67, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (52, 'Firebreaks', 120.07, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (53, 'Sanitation', 895.74, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (54, 'Signposting', 758.86, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (55, 'Signposting', 755.19, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (56, 'Pruning', 840.13, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (57, 'Sanitation', 387.04, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (58, 'Sanitation', 159.15, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (59, 'Burning the Cuttings', 863.16, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (60, 'Signposting', 496.27, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (61, 'access roads', 270.58, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (62, 'access roads', 18.69, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (63, 'Removing the Cuttings and the Tree Waste', 859.65, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (64, 'Firebreaks', 263.27, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (65, 'access roads', 570.05, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (66, 'Firebreaks', 550.09, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (67, 'Burning the Cuttings', 942.62, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (68, 'access roads', 957.72, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (69, 'access roads', 926.81, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (70, 'Water', 942.4, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (71, 'Signposting', 922.59, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (72, 'Burning the Cuttings', 696.64, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (73, 'Sanitation', 281.18, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (74, 'Watchtowers', 4.8, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (75, 'Burning the Cuttings', 623.16, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (76, 'Sanitation', 449.29, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (77, 'Removing the Cuttings and the Tree Waste', 833.62, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (78, 'Burning the Cuttings', 182.17, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (79, 'Pruning', 551.11, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (80, 'Pruning', 776.81, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (81, 'Thinning', 579.06, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (82, 'Sanitation', 884.83, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (83, 'Burning the Cuttings', 487.29, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (84, 'Water', 173.68, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (85, 'Sanitation', 456.99, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (86, 'Thinning', 574.58, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (87, 'Removing the Cuttings and the Tree Waste', 70.77, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (88, 'Signposting', 801.06, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (89, 'Thinning', 721.98, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (90, 'Watchtowers', 88.59, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (91, 'Firebreaks', 590.69, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (92, 'Thinning', 731.15, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (93, 'access roads', 219.8, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (94, 'Water', 167.73, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (95, 'Watchtowers', 596.2, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (96, 'Watchtowers', 802.37, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (97, 'Burning the Cuttings', 362.19, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (98, 'Firebreaks', 569.04, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (99, 'Watchtowers', 355.29, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (100, 'Pruning', 377.63, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (101, 'Pruning', 801.93, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (102, 'Sanitation', 747.55, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (103, 'Burning the Cuttings', 653.32, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (104, 'Firebreaks', 908.6, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (105, 'Firebreaks', 288.25, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (106, 'Sanitation', 703.31, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (107, 'access roads', 23.64, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (108, 'Removing the Cuttings and the Tree Waste', 326.42, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (109, 'Burning the Cuttings', 719.38, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (110, 'Water', 534.25, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (111, 'Sanitation', 561.87, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (112, 'access roads', 383.15, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (113, 'Pruning', 7.44, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (114, 'access roads', 605.25, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (115, 'Sanitation', 92.79, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (116, 'access roads', 380.77, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (117, 'Pruning', 629.11, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (118, 'Pruning', 12.87, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (119, 'Sanitation', 324.34, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (120, 'Pruning', 208.7, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (121, 'Thinning', 671.51, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (122, 'Removing the Cuttings and the Tree Waste', 22.74, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (123, 'Thinning', 925.12, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (124, 'Signposting', 205.54, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (125, 'Pruning', 80.97, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (126, 'Firebreaks', 67.77, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (127, 'Thinning', 583.61, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (128, 'Firebreaks', 390.84, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (129, 'Pruning', 968.0, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (130, 'access roads', 253.21, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (131, 'Removing the Cuttings and the Tree Waste', 393.2, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (132, 'Burning the Cuttings', 230.07, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (133, 'Sanitation', 473.57, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (134, 'Pruning', 427.4, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (135, 'Sanitation', 230.65, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (136, 'Sanitation', 767.18, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (137, 'Water', 915.71, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (138, 'Burning the Cuttings', 230.77, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (139, 'Signposting', 973.61, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (140, 'Signposting', 919.94, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (141, 'Sanitation', 148.12, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (142, 'Sanitation', 166.39, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (143, 'Removing the Cuttings and the Tree Waste', 986.47, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (144, 'Water', 105.71, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (145, 'Removing the Cuttings and the Tree Waste', 112.2, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (146, 'Removing the Cuttings and the Tree Waste', 187.93, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (147, 'Firebreaks', 446.97, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (148, 'access roads', 802.62, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (149, 'Water', 804.0, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (150, 'Water', 510.89, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (151, 'Signposting', 594.24, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (152, 'Signposting', 886.86, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (153, 'Sanitation', 256.57, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (154, 'Water', 420.29, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (155, 'Water', 958.86, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (156, 'Watchtowers', 911.91, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (157, 'Pruning', 944.91, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (158, 'Burning the Cuttings', 353.23, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (159, 'Removing the Cuttings and the Tree Waste', 940.91, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (160, 'access roads', 626.58, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (161, 'Watchtowers', 21.1, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (162, 'Pruning', 480.17, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (163, 'access roads', 551.71, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (164, 'Pruning', 736.18, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (165, 'Burning the Cuttings', 715.71, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (166, 'Thinning', 439.09, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (167, 'Sanitation', 221.57, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (168, 'Watchtowers', 605.93, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (169, 'Burning the Cuttings', 179.39, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (170, 'Water', 883.01, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (171, 'Water', 857.71, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (172, 'Signposting', 637.75, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (173, 'access roads', 379.83, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (174, 'Watchtowers', 769.09, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (175, 'Removing the Cuttings and the Tree Waste', 815.95, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (176, 'Burning the Cuttings', 605.64, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (177, 'Burning the Cuttings', 402.47, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (178, 'Removing the Cuttings and the Tree Waste', 617.06, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (179, 'Thinning', 766.7, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (180, 'Signposting', 670.17, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (181, 'Watchtowers', 370.15, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (182, 'Removing the Cuttings and the Tree Waste', 441.08, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (183, 'Thinning', 880.34, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (184, 'Signposting', 918.49, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (185, 'Firebreaks', 127.46, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (186, 'Burning the Cuttings', 883.09, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (187, 'Pruning', 564.27, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (188, 'Removing the Cuttings and the Tree Waste', 858.01, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (189, 'Water', 674.51, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (190, 'Pruning', 194.46, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (191, 'Removing the Cuttings and the Tree Waste', 551.59, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (192, 'Firebreaks', 708.14, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (193, 'Signposting', 694.16, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (194, 'Watchtowers', 774.53, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (195, 'Thinning', 940.91, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (196, 'Watchtowers', 666.29, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (197, 'Pruning', 645.07, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (198, 'access roads', 806.83, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (199, 'Firebreaks', 256.27, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (200, 'Firebreaks', 707.57, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (201, 'access roads', 793.6, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (202, 'Watchtowers', 805.98, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (203, 'Water', 79.26, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (204, 'Water', 513.88, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (205, 'Firebreaks', 58.84, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (206, 'Water', 834.42, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (207, 'Removing the Cuttings and the Tree Waste', 106.84, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (208, 'Burning the Cuttings', 934.33, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (209, 'Burning the Cuttings', 251.56, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (210, 'Burning the Cuttings', 690.76, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (211, 'Thinning', 503.11, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (212, 'Pruning', 223.35, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (213, 'Watchtowers', 182.52, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (214, 'Water', 634.55, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (215, 'Firebreaks', 394.49, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (216, 'Burning the Cuttings', 846.08, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (217, 'Water', 875.28, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (218, 'Removing the Cuttings and the Tree Waste', 660.79, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (219, 'Burning the Cuttings', 778.16, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (220, 'Signposting', 439.02, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (221, 'Firebreaks', 433.11, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (222, 'access roads', 373.68, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (223, 'Pruning', 581.5, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (224, 'Signposting', 303.57, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (225, 'Sanitation', 936.31, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (226, 'Signposting', 363.37, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (227, 'access roads', 554.17, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (228, 'Firebreaks', 801.76, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (229, 'Signposting', 596.1, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (230, 'access roads', 937.2, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (231, 'Burning the Cuttings', 717.38, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (232, 'access roads', 672.87, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (233, 'Sanitation', 216.15, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (234, 'Thinning', 389.08, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (235, 'Sanitation', 308.34, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (236, 'Firebreaks', 360.12, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (237, 'Burning the Cuttings', 410.81, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (238, 'Thinning', 958.72, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (239, 'Water', 793.4, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (240, 'Watchtowers', 485.05, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (241, 'Sanitation', 152.49, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (242, 'Pruning', 629.41, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (243, 'Burning the Cuttings', 930.4, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (244, 'Removing the Cuttings and the Tree Waste', 583.29, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (245, 'Sanitation', 255.53, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (246, 'access roads', 745.07, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (247, 'Burning the Cuttings', 806.36, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (248, 'Water', 800.76, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (249, 'Pruning', 196.24, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (250, 'Watchtowers', 191.55, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (251, 'access roads', 522.1, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (252, 'Burning the Cuttings', 979.51, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (253, 'Signposting', 573.44, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (254, 'Removing the Cuttings and the Tree Waste', 213.2, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (255, 'Thinning', 715.44, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (256, 'Removing the Cuttings and the Tree Waste', 820.16, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (257, 'Thinning', 16.53, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (258, 'Sanitation', 247.28, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (259, 'Water', 20.86, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (260, 'Firebreaks', 195.45, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (261, 'Water', 611.75, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (262, 'Watchtowers', 825.75, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (263, 'access roads', 359.4, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (264, 'Burning the Cuttings', 622.97, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (265, 'Pruning', 324.8, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (266, 'Signposting', 190.62, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (267, 'Removing the Cuttings and the Tree Waste', 955.84, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (268, 'Water', 558.78, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (269, 'Signposting', 60.71, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (270, 'Watchtowers', 146.32, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (271, 'Water', 757.48, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (272, 'Thinning', 194.94, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (273, 'access roads', 853.73, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (274, 'Pruning', 942.12, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (275, 'Firebreaks', 389.92, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (276, 'Removing the Cuttings and the Tree Waste', 166.85, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (277, 'Firebreaks', 510.31, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (278, 'Removing the Cuttings and the Tree Waste', 617.12, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (279, 'Sanitation', 109.01, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (280, 'Burning the Cuttings', 969.38, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (281, 'Sanitation', 325.73, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (282, 'Burning the Cuttings', 890.81, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (283, 'Water', 641.59, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (284, 'Water', 165.04, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (285, 'Water', 116.72, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (286, 'Removing the Cuttings and the Tree Waste', 663.38, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (287, 'Firebreaks', 130.69, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (288, 'Firebreaks', 297.57, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (289, 'Water', 645.42, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (290, 'Sanitation', 299.08, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (291, 'Burning the Cuttings', 453.03, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (292, 'Sanitation', 630.09, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (293, 'Removing the Cuttings and the Tree Waste', 842.79, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (294, 'Pruning', 560.55, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (295, 'Sanitation', 69.33, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (296, 'Sanitation', 662.92, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (297, 'Pruning', 852.36, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (298, 'Burning the Cuttings', 701.18, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (299, 'Sanitation', 452.27, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (300, 'access roads', 260.47, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (301, 'Removing the Cuttings and the Tree Waste', 610.86, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (302, 'Water', 522.29, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (303, 'Watchtowers', 183.52, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (304, 'Watchtowers', 655.22, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (305, 'Sanitation', 937.95, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (306, 'Watchtowers', 676.09, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (307, 'Sanitation', 439.08, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (308, 'Water', 893.95, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (309, 'access roads', 471.56, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (310, 'Thinning', 73.79, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (311, 'Removing the Cuttings and the Tree Waste', 403.32, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (312, 'access roads', 191.83, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (313, 'Burning the Cuttings', 51.2, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (314, 'Water', 558.09, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (315, 'Signposting', 526.04, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (316, 'Water', 50.65, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (317, 'Sanitation', 659.93, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (318, 'Water', 600.56, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (319, 'Signposting', 94.73, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (320, 'Signposting', 968.82, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (321, 'Water', 949.87, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (322, 'Sanitation', 34.59, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (323, 'Signposting', 587.05, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (324, 'Signposting', 278.05, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (325, 'Water', 673.27, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (326, 'access roads', 969.23, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (327, 'Thinning', 949.17, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (328, 'Watchtowers', 290.43, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (329, 'Sanitation', 442.56, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (330, 'Firebreaks', 587.63, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (331, 'Thinning', 124.79, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (332, 'Burning the Cuttings', 424.4, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (333, 'Water', 445.7, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (334, 'Firebreaks', 192.61, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (335, 'Sanitation', 774.84, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (336, 'Water', 747.64, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (337, 'Firebreaks', 283.27, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (338, 'Burning the Cuttings', 407.21, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (339, 'Thinning', 83.97, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (340, 'Sanitation', 82.17, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (341, 'Water', 188.77, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (342, 'Signposting', 162.75, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (343, 'access roads', 712.8, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (344, 'Burning the Cuttings', 610.33, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (345, 'Thinning', 71.19, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (346, 'Removing the Cuttings and the Tree Waste', 761.36, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (347, 'Sanitation', 796.81, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (348, 'Removing the Cuttings and the Tree Waste', 980.6, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (349, 'Sanitation', 741.65, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (350, 'Water', 702.61, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (351, 'Burning the Cuttings', 992.02, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (352, 'Pruning', 728.26, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (353, 'Sanitation', 68.36, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (354, 'Water', 980.01, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (355, 'Removing the Cuttings and the Tree Waste', 265.13, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (356, 'Sanitation', 466.54, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (357, 'Signposting', 22.29, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (358, 'Thinning', 721.22, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (359, 'Burning the Cuttings', 598.06, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (360, 'Water', 543.08, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (361, 'Water', 255.55, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (362, 'Thinning', 473.21, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (363, 'Burning the Cuttings', 473.52, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (364, 'Removing the Cuttings and the Tree Waste', 395.41, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (365, 'Watchtowers', 150.48, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (366, 'Firebreaks', 334.09, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (367, 'Thinning', 796.92, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (368, 'access roads', 666.52, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (369, 'Pruning', 280.59, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (370, 'Firebreaks', 445.75, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (371, 'Watchtowers', 313.42, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (372, 'Thinning', 40.48, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (373, 'Thinning', 373.87, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (374, 'access roads', 351.34, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (375, 'Burning the Cuttings', 831.18, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (376, 'Signposting', 884.47, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (377, 'Signposting', 998.44, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (378, 'access roads', 371.91, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (379, 'Thinning', 112.0, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (380, 'Firebreaks', 915.59, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (381, 'Signposting', 510.61, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (382, 'Pruning', 956.02, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (383, 'Burning the Cuttings', 4.49, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (384, 'Pruning', 291.24, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (385, 'Water', 292.33, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (386, 'Thinning', 722.66, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (387, 'Pruning', 6.49, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (388, 'Sanitation', 734.5, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (389, 'access roads', 563.54, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (390, 'Firebreaks', 921.55, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (391, 'Sanitation', 174.18, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (392, 'access roads', 892.95, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (393, 'Burning the Cuttings', 150.6, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (394, 'Pruning', 689.11, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (395, 'Watchtowers', 702.43, 'strong protection for a long time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (396, 'Burning the Cuttings', 29.13, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (397, 'access roads', 823.98, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (398, 'Signposting', 744.76, 'medium protection for a while');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (399, 'Pruning', 104.55, 'low protection for a short time');
insert into FOREST_FIRE_PREVENTION_ACTIONS (ACTION_ID, ACTION_NAME, COST, ACTION_DESCRIPTION) values (400, 'Signposting', 490.25, 'medium protection for a while');
